export type RightsStatus = "Public domain" | "Licensed" | "Rights review";
export type AssetStatus = "Print ready" | "Restoration needed" | "Source requested";

export type NewspaperRecord = {
  id: string;
  issueDate: string;
  publication: string;
  city: string;
  region: string;
  country: string;
  headline: string;
  summary: string;
  edition: string;
  occasion: "Birthday" | "Anniversary" | "History" | "Sports" | "Hometown";
  decade: string;
  language: string;
  keywords: string[];
  rightsStatus: RightsStatus;
  assetStatus: AssetStatus;
  sourceReference: string;
  featured?: boolean;
  accent: "red" | "green" | "blue" | "gold";
};

export const printSizes = [
  { label: "18 × 24 in", price: 64, note: "Classic wall print" },
  { label: "24 × 36 in", price: 89, note: "Most popular" },
  { label: "30 × 40 in", price: 119, note: "Statement size" },
] as const;

export const catalog: NewspaperRecord[] = [
  {
    id: "chi-1969-07-21-moon",
    issueDate: "1969-07-21",
    publication: "The Daily Record",
    city: "Chicago",
    region: "Illinois",
    country: "United States",
    headline: "Man Walks on the Moon",
    summary: "A generation looks skyward as the first lunar landing makes history.",
    edition: "Final City Edition",
    occasion: "History",
    decade: "1960s",
    language: "English",
    keywords: ["moon", "Apollo 11", "space", "NASA"],
    rightsStatus: "Rights review",
    assetStatus: "Print ready",
    sourceReference: "ARCH-CHI-1969-0721",
    featured: true,
    accent: "red",
  },
  {
    id: "nyc-1945-05-08-victory",
    issueDate: "1945-05-08",
    publication: "The Metropolitan Ledger",
    city: "New York",
    region: "New York",
    country: "United States",
    headline: "Victory in Europe",
    summary: "Crowds gather as the end of war in Europe is announced.",
    edition: "Extra Edition",
    occasion: "History",
    decade: "1940s",
    language: "English",
    keywords: ["VE Day", "victory", "World War II", "Times Square"],
    rightsStatus: "Rights review",
    assetStatus: "Print ready",
    sourceReference: "ARCH-NYC-1945-0508",
    featured: true,
    accent: "blue",
  },
  {
    id: "sf-1945-06-26-charter",
    issueDate: "1945-06-26",
    publication: "The Pacific Chronicle",
    city: "San Francisco",
    region: "California",
    country: "United States",
    headline: "A New Charter for the World",
    summary: "Delegates sign the United Nations Charter in San Francisco.",
    edition: "Home Edition",
    occasion: "History",
    decade: "1940s",
    language: "English",
    keywords: ["United Nations", "charter", "diplomacy", "peace"],
    rightsStatus: "Rights review",
    assetStatus: "Print ready",
    sourceReference: "ARCH-SFO-1945-0626",
    featured: true,
    accent: "green",
  },
  {
    id: "bos-1918-11-11-armistice",
    issueDate: "1918-11-11",
    publication: "The Boston Evening Gazette",
    city: "Boston",
    region: "Massachusetts",
    country: "United States",
    headline: "Armistice Signed",
    summary: "Church bells ring and city streets fill as the Great War comes to an end.",
    edition: "Noon Extra",
    occasion: "History",
    decade: "1910s",
    language: "English",
    keywords: ["armistice", "World War I", "peace", "veterans"],
    rightsStatus: "Public domain",
    assetStatus: "Print ready",
    sourceReference: "LOC-BOS-1918-1111",
    featured: true,
    accent: "gold",
  },
  {
    id: "stl-1904-04-30-fair",
    issueDate: "1904-04-30",
    publication: "The Gateway Herald",
    city: "St. Louis",
    region: "Missouri",
    country: "United States",
    headline: "World's Fair Opens Today",
    summary: "St. Louis welcomes the world for an extraordinary international exposition.",
    edition: "Morning Edition",
    occasion: "Hometown",
    decade: "1900s",
    language: "English",
    keywords: ["World's Fair", "exposition", "St. Louis", "1904"],
    rightsStatus: "Public domain",
    assetStatus: "Print ready",
    sourceReference: "LOC-STL-1904-0430",
    accent: "gold",
  },
  {
    id: "kit-1903-12-18-flight",
    issueDate: "1903-12-18",
    publication: "The Carolina Coastal News",
    city: "Kitty Hawk",
    region: "North Carolina",
    country: "United States",
    headline: "Machine Flies at Kitty Hawk",
    summary: "A powered aircraft rises from the dunes and changes travel forever.",
    edition: "Morning Edition",
    occasion: "History",
    decade: "1900s",
    language: "English",
    keywords: ["Wright brothers", "flight", "aviation", "airplane"],
    rightsStatus: "Public domain",
    assetStatus: "Print ready",
    sourceReference: "LOC-NC-1903-1218",
    accent: "blue",
  },
  {
    id: "det-1927-05-22-lindbergh",
    issueDate: "1927-05-22",
    publication: "The Great Lakes Journal",
    city: "Detroit",
    region: "Michigan",
    country: "United States",
    headline: "Lindbergh Reaches Paris",
    summary: "A solo Atlantic crossing ushers in a daring new age of aviation.",
    edition: "Sunday Final",
    occasion: "History",
    decade: "1920s",
    language: "English",
    keywords: ["Lindbergh", "Paris", "aviation", "Atlantic"],
    rightsStatus: "Public domain",
    assetStatus: "Print ready",
    sourceReference: "LOC-DET-1927-0522",
    accent: "green",
  },
  {
    id: "la-1984-07-29-olympics",
    issueDate: "1984-07-29",
    publication: "The Los Angeles Dispatch",
    city: "Los Angeles",
    region: "California",
    country: "United States",
    headline: "The Games Begin",
    summary: "Los Angeles lights the flame and welcomes athletes from around the world.",
    edition: "Sunday Edition",
    occasion: "Sports",
    decade: "1980s",
    language: "English",
    keywords: ["Olympics", "Los Angeles", "sports", "opening ceremony"],
    rightsStatus: "Licensed",
    assetStatus: "Print ready",
    sourceReference: "LIC-LAX-1984-0729",
    accent: "red",
  },
  {
    id: "atl-1996-07-20-games",
    issueDate: "1996-07-20",
    publication: "The Atlanta City Journal",
    city: "Atlanta",
    region: "Georgia",
    country: "United States",
    headline: "Atlanta Welcomes the World",
    summary: "The Centennial Olympic Games open in the heart of Georgia.",
    edition: "Weekend Edition",
    occasion: "Sports",
    decade: "1990s",
    language: "English",
    keywords: ["Olympics", "Atlanta", "sports", "centennial"],
    rightsStatus: "Licensed",
    assetStatus: "Print ready",
    sourceReference: "LIC-ATL-1996-0720",
    accent: "blue",
  },
  {
    id: "sea-1962-04-22-fair",
    issueDate: "1962-04-22",
    publication: "The Puget Sound Ledger",
    city: "Seattle",
    region: "Washington",
    country: "United States",
    headline: "Century 21 Opens",
    summary: "The Space Needle rises above Seattle as the World's Fair begins.",
    edition: "Sunday Edition",
    occasion: "Hometown",
    decade: "1960s",
    language: "English",
    keywords: ["Seattle", "World's Fair", "Space Needle", "Century 21"],
    rightsStatus: "Rights review",
    assetStatus: "Restoration needed",
    sourceReference: "ARCH-SEA-1962-0422",
    accent: "green",
  },
  {
    id: "mia-1969-01-13-superbowl",
    issueDate: "1969-01-13",
    publication: "The Miami Sun",
    city: "Miami",
    region: "Florida",
    country: "United States",
    headline: "Jets Shock the Football World",
    summary: "An unforgettable championship upset takes center stage in Miami.",
    edition: "Morning Sports Final",
    occasion: "Sports",
    decade: "1960s",
    language: "English",
    keywords: ["football", "Super Bowl", "Jets", "championship"],
    rightsStatus: "Rights review",
    assetStatus: "Print ready",
    sourceReference: "ARCH-MIA-1969-0113",
    accent: "blue",
  },
  {
    id: "hou-1969-07-25-home",
    issueDate: "1969-07-25",
    publication: "The Houston Star",
    city: "Houston",
    region: "Texas",
    country: "United States",
    headline: "Apollo Crew Home Safe",
    summary: "The Apollo 11 astronauts return safely after their lunar voyage.",
    edition: "Evening Edition",
    occasion: "Hometown",
    decade: "1960s",
    language: "English",
    keywords: ["Apollo 11", "Houston", "splashdown", "astronauts"],
    rightsStatus: "Rights review",
    assetStatus: "Print ready",
    sourceReference: "ARCH-HOU-1969-0725",
    accent: "red",
  },
  {
    id: "phi-1776-07-08-declaration",
    issueDate: "1776-07-08",
    publication: "The Pennsylvania Evening Post",
    city: "Philadelphia",
    region: "Pennsylvania",
    country: "United States",
    headline: "Declaration Read to the People",
    summary: "Philadelphia hears a public reading of the Declaration of Independence.",
    edition: "Evening Edition",
    occasion: "History",
    decade: "1770s",
    language: "English",
    keywords: ["Declaration", "independence", "Philadelphia", "American Revolution"],
    rightsStatus: "Public domain",
    assetStatus: "Print ready",
    sourceReference: "LOC-PHL-1776-0708",
    accent: "gold",
  },
  {
    id: "dc-1963-08-29-dream",
    issueDate: "1963-08-29",
    publication: "The Capital Bulletin",
    city: "Washington",
    region: "District of Columbia",
    country: "United States",
    headline: "A Dream Echoes Across the Nation",
    summary: "The March on Washington becomes a defining moment in the civil rights movement.",
    edition: "Morning Edition",
    occasion: "History",
    decade: "1960s",
    language: "English",
    keywords: ["March on Washington", "civil rights", "Lincoln Memorial", "dream"],
    rightsStatus: "Rights review",
    assetStatus: "Source requested",
    sourceReference: "REQ-DC-1963-0829",
    accent: "red",
  },
  {
    id: "chi-2016-11-03-series",
    issueDate: "2016-11-03",
    publication: "The Chicago Daily Record",
    city: "Chicago",
    region: "Illinois",
    country: "United States",
    headline: "At Last! Chicago Celebrates",
    summary: "A historic baseball championship ends a 108-year wait.",
    edition: "Championship Edition",
    occasion: "Sports",
    decade: "2010s",
    language: "English",
    keywords: ["Chicago", "baseball", "championship", "World Series"],
    rightsStatus: "Licensed",
    assetStatus: "Print ready",
    sourceReference: "LIC-CHI-2016-1103",
    accent: "blue",
  },
  {
    id: "nyc-2001-09-12-remembrance",
    issueDate: "2001-09-12",
    publication: "The Metropolitan Ledger",
    city: "New York",
    region: "New York",
    country: "United States",
    headline: "A City Stands Together",
    summary: "A solemn historic edition documenting a day of national tragedy and resilience.",
    edition: "Special Edition",
    occasion: "History",
    decade: "2000s",
    language: "English",
    keywords: ["New York", "September 11", "remembrance", "history"],
    rightsStatus: "Rights review",
    assetStatus: "Restoration needed",
    sourceReference: "ARCH-NYC-2001-0912",
    accent: "green",
  },
];

export const formatIssueDate = (date: string) =>
  new Intl.DateTimeFormat("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
    timeZone: "UTC",
  }).format(new Date(`${date}T00:00:00Z`));

export const uniqueDecades = [...new Set(catalog.map((item) => item.decade))].sort(
  (a, b) => Number(b.slice(0, 4)) - Number(a.slice(0, 4)),
);

export const uniqueRegions = [...new Set(catalog.map((item) => item.region))].sort();
